# Generated by Django 4.1.2 on 2022-11-10 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='rg',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
