# Generated by Django 4.1.2 on 2022-11-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_alter_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=14, null=True, unique=True),
        ),
    ]
