# Generated by Django 4.1.2 on 2022-12-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_student_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='rg',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
